创建异常

使用 throw 关键字创建异常：

throw value

一旦 JavaScript 执行到此行，则常规的程序流会被停止，且控制会被交给最近的异常处理程序。

通常，在客户端代码中，value 可以是任何 JavaScript 值（包括字符串、数字、或对象）。

在 Node.js 中，我们不抛出字符串，而仅抛出 Error 对象。

错误对象

错误对象是 Error 对象的实例、或者继承自 Error 类（由 Error 核心模块提供）：

throw new Error('错误信息')

或：

class NotEnoughCoffeeError extends Error {
  //...
}
throw new NotEnoughCoffeeError()

处理异常

异常处理程序是 try/catch 语句。

try 块中包含的代码行中引发的任何异常都会在相应的 catch 块中处理：

try {
  //代码行
} catch (e) {}

在此示例中，e 是异常值。

可以添加多个处理程序，它们可以捕获各种错误。

